### ISSUE TITLE
RCON not workin

### ISSUE THREAD

**Issue by Pablo-Barros** [CM2Walki/CS2#11]
I setted the rcon password on my client with rcon_password [password] command and it's also set on the docker env variables, but when I try to use the rcon command on the client, even rcon status it  returns: Unable to connect to remote server (_ip_)

I tried also with rcon clients, no only in-game commands and also tried to set a custom port on the docker env variables

**Comment by CM2Walki** [comment]
If this issue is still relevant, reopen it on [joedwards32/CS2](https://github.com/joedwards32/CS2). This repository is now a mirror.
