### ISSUE TITLE
CM2Walki / CSGO Docker deployment

### ISSUE THREAD

**Issue by misty-windy** [CM2Walki/CS2#13]
Now I want to use CM2Walki/CSGO to deploy the dedicated server for csgo, The exclusive server for CSGO is 740，Is the project code still using 730？

UPDATE：After deployment, I checked the logs and found that the game service has been restarting in a loop

**Comment by misty-windy** [comment]
![Uploading csgo.png…]()

**Comment by misty-windy** [comment]
![csgo](https://github.com/CM2Walki/CS2/assets/40721604/0bec8d23-462f-41d3-b5b6-2a9053920aca)

**Comment by CM2Walki** [comment]
If this issue is still relevant, reopen it on [joedwards32/CS2](https://github.com/joedwards32/CS2). This repository is now a mirror.
