### ISSUE TITLE
Merge CS2 repositories

### ISSUE THREAD

**Issue by CM2Walki** [CM2Walki/CS2#3]
This is issue tracks merge progress of https://github.com/joedwards32/CS2 into https://github.com/CM2Walki/CS2.

**Comment by joedwards32** [comment]
@CM2Walki, I've not had a chance to look at this yet. Will try to find some time tomorrow.

**Comment by almereyda** [comment]
Will the it remain available that one can use the `steamcmd` workflow to persist an authenticated Steam session to disk? It doesn't seem available in the other repository.

Last time I tried it, it didn't work:

- https://github.com/CM2Walki/steamcmd/issues/50

I'm available to test any developments on this merger, esp. due to the limitation presented by the issue, which blocked me from successfully running a CS2 service.

**Comment by CM2Walki** [comment]
I think this fork has become obsolete. Although the csgo image used to be my most popular repository, I simply no longer have time to maintain a project like that. I'd rather focus on my steamcmd repository.

@joedwards32 you've done a great job with your repository and I think it's just easier to continue there. I can offer you the use of my team plan on Docker Hub (cm2network), so your image would appear as Docker Sponsored OSS, of course the repository would still be yours (I would also redirect all my links to your repo).

Let me know what you think.

**Comment by joedwards32** [comment]
@CM2Walki I'm happy to continue with my fork and any assistance you are willing to offer, be that Docker Hub team plan or PRs, is much appreciated.

**Comment by almereyda** [comment]
Just to confirm, the current upstream is

* [joedwards32/CS2: CS2 Dedicated Server Docker Image](https://github.com/joedwards32/CS2)

and the Docker images in

* [joedwards32/cs2 - Docker Image | Docker Hub](https://hub.docker.com/r/joedwards32/cs2)

are recommended over `cm2network/cs2` *only until* this rewiring is in place, when both will be the same or `joedwards32/cs2` even depreciated. Am I correct?

**Comment by CM2Walki** [comment]
I see two options, both keep backwards compatibility.

1. I make this repository an automated mirror of [joedwards32/CS2](https://github.com/joedwards32/CS2) and just maintain the docker auto build being pushed to `cm2network/cs2` in which case `joedwards32/cs2` will always be identical, so you could use either.
2. I archive this repository and setup docker auto build on [joedwards32/CS2](https://github.com/joedwards32/CS2) that pushes to `cm2network/cs2`, this would happen in addition to the current github action pushing to `joedwards32/cs2`, so you could use either again.

@joedwards32 give me a heads up which version you prefer. I prefer option 2 since collaboration would be easier simplified.

**Comment by joedwards32** [comment]
Option 2 works for me :)

**Comment by almereyda** [comment]
Some concern will have to be put into bringing the Readmes on Docker Hub into good shape. I remember they are mostly left out from synchronisations and rely on manual intervention for updating. Please have a second look at that when you're done, else I fear it might be easily overlooked.

**Comment by CM2Walki** [comment]
If you link a repository via docker hub auto builds, the readme will automatically be updated with an image push. The desync only happens if you manually push an image via a different pipeline.

**Comment by CM2Walki** [comment]
> Option 2 works for me :)

Cool 😄. Could you add me as a contributor on https://github.com/joedwards32/CS2, please?

**Comment by joedwards32** [comment]
Invite on the way.

**Comment by CM2Walki** [comment]
Thanks.

![image](https://github.com/CM2Walki/CS2/assets/12199415/0a243b42-e13e-4ca4-bf53-9cd424e1b824)
I tried changing the source repository on docker hub, but it only detects my fork, not your repository.

There's 3 paths forward:

1. I turn this repository into a mirror of yours, which will automatically propagate to `cm2network/cs2` and we just collaborate on https://github.com/joedwards32/CS2 (I prefer this one 😅).
2. I delete my `cm2network/cs2` docker hub repository and you recreate it once you're a member of the `cm2network` organization.

**Comment by CM2Walki** [comment]
@joedwards32 this repository is now a mirror of yours. I'm syncing the fork every 5 minutes and the docker hub autobuilds still work.
