### ISSUE TITLE
Support for Workshop maps

### ISSUE THREAD

**Issue by simon96aic** [CM2Walki/CS2#7]
Hello,
Workshop maps are now supported again with the latest update.
![Screenshot_2023-11-03-06-55-32-424_com android chrome-edit](https://github.com/CM2Walki/CS2/assets/6340498/8e913caa-544b-473c-b97a-90e1ad2d4be5)

**Comment by carlosgeos** [comment]
You can easily host workshop maps using RCON:
```
host_workshop_map <workshop id>
```

**Comment by Urferu** [comment]
No, it detects the rcon commands since I started the dedicated server

**Comment by carlosgeos** [comment]
I wasn't able to issue RCON commands in-game, but I could using one of these two RCON clients (from the same host, connecting to 127.0.1.1):

https://github.com/forewing/csgo-rcon
https://github.com/gorcon/rcon-cli

**Comment by Izocel** [comment]
The rcon commands works fine, but are you guys planing on adding the docker environement for collections and workshop maps like with the csgo docker ? Also, cna we push it in the entry.sh until then ? Is it already managed by the entry.sh ?

**Comment by CM2Walki** [comment]
If this issue is still relevant, reopen it on [joedwards32/CS2](https://github.com/joedwards32/CS2). This repository is now a mirror.
