### ISSUE TITLE
Game token

### ISSUE THREAD

**Issue by dollar62** [CM2Walki/CS2#8]
Hello as the title says, i get the message that there's no game token, so the server will only function in LAN-mode. I cannot see any where in this guide about the game token.

Thanks

**Comment by yannickvr** [comment]
I got it to work by creating a token here: https://steamcommunity.com/dev/managegameservers

And then use that token with `CS2_ADDITIONAL_ARGS=+sv_setsteamaccount <yourtoken>` 

In my mind the token that is created with STEAMCMD should work as well, but I cannot find why that's not the case. Just using `STEAMUSER=myusername` shows incorrect password on starting the server.

**Comment by CM2Walki** [comment]
Closed by #9.
